---
title: "Practice model"
output: html_notebook
---

Just a quick, lousy kind of model to see how it's done. Plan of attack: bring in "used" points, bring in small number of "available" points (which I now realized I selected wrong, but hey, that's why this is a practice run), join them together with a 0/1 to indicate which pool they come from, explore the data a little, then run through a logistic regression.

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Load some libraries.
library('tidyverse')

# Load the data.
used <- read.csv('../data/processed/h_roost_attributes.csv')
avail <- read.csv('../data/processed/ska_random_variables.csv')

# Clean up the used columns.
used <- used %>% dplyr::select(-day) %>%
  rename(ycoord=m.lat, xcoord=m.lon) %>%
  mutate(case=1)

# Add a case column to the available points, too.
avail <- avail %>%
  mutate(case=0)

# Bind them together.
points <- bind_rows(used, avail)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
